const namespaces = 'transactions';

const Types = {
  TRANSACTION_LISTING_REQUEST: `${namespaces}/TRANSACTION_LISTING_REQUEST`,
  TRANSACTION_DETAILS_REQUEST: `${namespaces}/TRANSACTION_DETAILS_REQUEST`,
  TRANSACTION_INITIATE_REQUEST: `${namespaces}/TRANSACTION_INITIATE_REQUEST`,
  TRANSACTION_CREATE_REQUEST: `${namespaces}/TRANSACTION_CREATE_REQUEST`,
  TRANSACTION_CHECK_TOKEN: `${namespaces}/TRANSACTION_CHECK_TOKEN`,
  TRANSACTION_PAYMENT_SUBSCRIBE: `${namespaces}/TRANSACTION_PAYMENT_SUBSCRIBE`,
  TRANSACTION_CANCEL_SUBSCRIPTION: `${namespaces}/TRANSACTION_CANCEL_SUBSCRIPTION`,
  TRANSACTION_TOKEN_PRIZE: `${namespaces}/TRANSACTION_TOKEN_PRIZE`,
  PRICING_PLANS: `${namespaces}/PRICING_PLANS`,
  PLAN_CHECKOUT: `${namespaces}/PLAN_CHECKOUT`,
  PAYMENT_VERIFICATION: `${namespaces}/PAYMENT_VERIFICATION`,
};

export default Types;
